### ISSUE TITLE
I am attempting to display for multiple teams but not working

### ISSUE THREAD

**Issue by shak4031** [cowboysdude/MMM-MLB#7]
I attempted to provide all three teams as per config sample and only the 1st team scores are displayed.  I then created 3 configs, one per team and that again only displayed the first team scores.

{
                        module: "MMM-MLB",
                        position: "bottom_left",
                        config: { // See "Configuration options" for more information.
                        maxWidth: "400px",
                        header: true,
                        logo: true,
                        focus_on: ["Yankees"]
                        }
                },
                {
                        module: "MMM-MLB",
                        position: "bottom_left",
                        config: { // See "Configuration options" for more information.
                        maxWidth: "400px",
                        header: true,
                        logo: true,
                        focus_on: ["Toronto"]
                        }
                },
                {
                        module: "MMM-MLB",
                        position: "bottom_left",
                        config: { // See "Configuration options" for more information.
                        maxWidth: "400px",
                        header: true,
                        logo: true,
                        focus_on: ["Boston"]
                        }
                },

OR

{
                        module: "MMM-MLB",
                        position: "bottom_left",
                        config: { // See "Configuration options" for more information.
                        maxWidth: "400px",
                        header: true,
                        logo: true,
                        focus_on: ["Yankees" ,"Boston", "Toronto"]
                        }
                },

**Comment by shak4031** [comment]
I am seeing this error in the logs:

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at /home/pi/MagicMirror/modules/MMM-MLB/node_helper.js:88:22
0|mm       |     at ClientRequest.<anonymous> (/home/pi/MagicMirror/modules/MMM-MLB/node_helper.js:31:31)
0|mm       |     at ClientRequest.emit (events.js:315:20)
0|mm       |     at TLSSocket.socketCloseListener (_http_client.js:385:9)
0|mm       |     at TLSSocket.emit (events.js:327:22)
0|mm       |     at net.js:674:12
0|mm       |     at TCP.done (_tls_wrap.js:567:7)
0|mm       | [15.09.2021 13:26.14.458] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [15.09.2021 13:26.14.458] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
